@host = https://sammlungsportal.bua-dns.de

# ----  DIRECTUS API ----

### Get theme contents
GET {{host}}/items/theme_content?limit=-1

### Get background images
GET {{host}}/items/background_images?limit=-1

### Get all collection items
GET {{host}}/items/bua_collections?limit=-1&sort=label&meta=total_count

### Get all collection items with collection files
GET {{host}}/items/bua_collections?fields=*.directus_files_id.*.*&limit=-1&sort=label&meta=total_count

### Get collections filtered by current_keeper
GET {{host}}/items/bua_collections?limit=-1&sort=label&filter[current_keeper][_eq]=Freie Universität Berlin

### Get pages
GET {{host}}/items/pages?fields=*,translations.*&limit=-1

### Get a page by slug
GET {{host}}/items/pages?fields=*,translations.*&filter[slug][_eq]=projekte

### Get homepage
GET {{host}}/items/homepage

### Get homepage with navigation cards
GET {{host}}/items/homepage?fields=*.navigation_cards_id.*.*

### homepage
GET {{host}}/items/homepage?fields=title,cardset_collections.navigation_cards_id.*.*,cardset_featured.navigation_cards_id.*.*,intro,cardset_collections_intro,subject_selection_intro,object_type_selection_intro,cardset_featured_intro

### taxonomy_terms
GET {{host}}/items/taxonomy_terms?fields=id,label,spws_taxonomy&limit=-1&meta=total_count