@host = https://sammlungsportal.bua-dns.de

# ----  DIRECTUS API ----

### Get theme contents
GET {{host}}/items/theme_content?limit=-1

### Get background images
GET {{host}}/items/background_images?limit=-1

### Get all collection items
GET {{host}}/items/bua_collections?limit=-1&sort=label&meta=total_count

### Get all collection items with collection files
GET {{host}}/items/bua_collections?fields=*.directus_files_id.*.*&limit=-1&sort=label&meta=total_count

### Get collections filtered by current_keeper
GET {{host}}/items/bua_collections?limit=-1&sort=label&filter[current_keeper][_eq]=Freie Universität Berlin

### Get pages
GET {{host}}/items/pages?limit=-1

### Get a page by slug
GET {{host}}/items/pages?filter[slug][_eq]=imprint

### Get homepage
GET {{host}}/items/homepage

### Get homepage with navigation cards
GET {{host}}/items/homepage?fields=*.navigation_cards_id.*.*